config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :my_searches
  resources :articles do
    collection do
      post :search
    end
  end
  resources :users, only: %i[show create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
  scope :search_item, ->(title) { where('title ILIKE ?', "%#{title}%") }
end

app/models/my_search.rb
class MySearch < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { maximum: 500, minimum: 3 }
  scope :saved_search, -> { select(:body).distinct }
end

app/models/searches.rb
class Searches
  # the save_query function compares the last saved search to the new search,
  # divide the search by two to see if the first part match the replace and update
  # The search and user id is saved in the my_search database.

  def initialize(search, user_id)
    @search = search
    @user_id = user_id
  end

  def save_query
    recent_search = MySearch.first
    if recent_search && equal(recent_search.body.downcase, @search.downcase)
      recent_search.body = @search
      recent_search.updated_at = DateTime.now if recent_search.body == @search
      recent_search.save!
      return recent_search
    end

    MySearch.create! body: @search, user_id: @user_id
  end

  private

  def equal(first_query, second_query)
    query_count(first_query, second_query) > 0.5
  end

  def query_count(first_query, second_query)
    count = 0
    unwanted_index = []
    first_query.each_char.with_index do |_c, i|
      break if unwanted_index.length == second_query.length

      query2_value = find_index second_query, first_query[i], unwanted_index
      next unless query2_value

      unwanted_index.append query2_value

      dist = 2**-(i - query2_value).abs
      count += dist if dist >= 0.01
    end

    length = first_query.length < second_query.length ? first_query.length : second_query.length
    count.to_f / length
  end

  def find_index(str, target, unwanted_index = [])
    next_ = 0
    loop do
      i = str[next_..].index target
      return nil unless i

      i += next_
      return i unless unwanted_index.include? i

      next_ = i + 1
      return nil if next_ >= str.length
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :my_searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:full_name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:full_name, :email, :password, :current_password)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  # Here users search and save their search
  def search
    @articles = if params[:content_search].present?
                  Searches.new(params[:content_search], current_user.id).save_query
                  Article.search_item(params[:content_search])
                else
                  []
                end
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update('search_results',
                                                 partial: 'articles/search_results', locals: { articles: @articles })
      end
    end
  end
end

app/controllers/my_searches_controller.rb
class MySearchesController < ApplicationController
  def index
    # only the create of the search to see what they searched
    @top_searches = MySearch.saved_search.where(user: current_user)
  end

  def clear_searches
    My_search.destroy_all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/my_searches_helper.rb
module MySearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= article.content %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_search_form.html.erb
<div class="search-input">
  <div class="w-100">
    <%= form_with url: search_articles_path, method: :post, data: {controller: "query", query_target: "form" } do |form| %>
       <%= form.search_field :content_search, data: { action: "input->query#search" }, class: "form-control", placeholder: 'Search...' %>
    <% end %>
    <div>
      <div id="search_results"></div>
    </div>
  </div>
</div>

app/views/articles/_search_results.html.erb
<%= articles.count %>
<% articles.each do |article| %>
  <br>
  <%= link_to highlight(article.title, params[:content_search]) %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div class="d-flex justify-content-center mt-5 align-items-center">
  <div>
    <div class="d-flex justify-content-between align-items-center">
    
      <%= render "articles/search_form" %>
  
      <div class="analyzer">
        <%= link_to 'Analysis', my_searches_path %>
      </div>

    </div>
    <p style="color: green"><%= notice %></p>

    <h1>Articles</h1>

    <div id="articles">
      <% @articles.each do |article| %>
        <%= render article %>
        <p>
          <%= link_to "Show this article", article %>
        </p>
      <% end %>
    </div>

    <%= link_to "New article", new_article_path %>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpjuiceTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"
      integrity="sha512-6PM0qYu5KExuNcKt5bURAoT6KCThUmHRewN3zUFNaoI6Di7XJPTMoT6K0nsagZKk2OB4L7E3q1uQKHNHd4stIQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
>   </script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="">
      <div class="">
        <div class="logout d-flex gap-2 gap-md-4 justify-content-between align-items-center">
          <% if current_user %>
            <%= link_to 'Log out', destroy_user_session_path, data: { turbo_method: :delete }, class: "login" %>
          <% else %>
            <%= link_to 'Log in', user_session_path, class: "login" %>
            <%= link_to 'Sign Up', new_user_registration_path, class: "get-start" %>
          <% end %>
        </div>
      </div>
        <% if notice.present? %>
          <div class="notice">
            <p class="bg-warning text-center text-white"> <%= notice %> </p>
          </div>
        <% end %>
        <% if alert.present? %>
          <div class="alert">
            <p class="bg-danger text-center text-white"> <%= alert %> </p>
          </div>
        <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/my_searches/index.html.erb
<h1>My searches</h1>

<div id="my_searches">
  <%if @top_searches.any?%>
    <% @top_searches.each do |search| %>

      <p><%= search.body %></p>
    <% end %>
  <% end %>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>